CartPole-v1:
  n_envs: 8
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: 0.0

MountainCar-v0:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: .0

Acrobot-v1:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: .0

# Tuned
Pendulum-v1:
  normalize: True
  n_envs: 8
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: 0.0
  max_grad_norm: 0.5
  n_steps: 8
  gae_lambda: 0.9
  vf_coef: 0.4
  gamma: 0.9
  use_rms_prop: True
  normalize_advantage: False
  learning_rate: lin_7e-4
  use_sde: True
  policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"

# === Mujoco Envs ===

HalfCheetah-v3: &mujoco-defaults
  normalize: true
  n_timesteps: !!float 1e6
  policy: "MlpPolicy"

HalfCheetah-v4:
  <<: *mujoco-defaults

Ant-v3:
  <<: *mujoco-defaults

Hopper-v3:
  <<: *mujoco-defaults

Walker2d-v3:
  <<: *mujoco-defaults

Humanoid-v3:
  <<: *mujoco-defaults
  n_timesteps: !!float 2e6

Swimmer-v3:
  <<: *mujoco-defaults
  gamma: 0.9999

# === FoRL Envs ===
FoRLCartPole-v0:
  n_envs: 8
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: 0.0

FoRLMountainCar-v0:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: .0

FoRLAcrobot-v0:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: .0

FoRLPendulum-v0:
  normalize: True
  n_envs: 8
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: 0.0
  max_grad_norm: 0.5
  n_steps: 8
  gae_lambda: 0.9
  vf_coef: 0.4
  gamma: 0.9
  use_rms_prop: True
  normalize_advantage: False
  learning_rate: lin_7e-4
  use_sde: True
  policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"

FoRLCartPoleRandomNormal-v0:
  n_envs: 8
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: 0.0

FoRLMountainCarRandomNormal-v0:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: .0

FoRLAcrobotRandomNormal-v0:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: .0

FoRLPendulumRandomNormal-v0:
  normalize: True
  n_envs: 8
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  ent_coef: 0.0
  max_grad_norm: 0.5
  n_steps: 8
  gae_lambda: 0.9
  vf_coef: 0.4
  gamma: 0.9
  use_rms_prop: True
  normalize_advantage: False
  learning_rate: lin_7e-4
  use_sde: True
  policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"

FoRLHalfCheetahRandomNormal-v0:
  <<: *mujoco-defaults

FoRLHalfCheetah-v0:
  <<: *mujoco-defaults

FoRLHopper-v0:
  <<: *mujoco-defaults

FoRLHopperRandomNormal-v0:
  <<: *mujoco-defaults
