# Tuned
# === Mujoco Envs ===

HalfCheetah-v3: &mujoco-defaults
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  learning_starts: 10000

Ant-v3:
  <<: *mujoco-defaults

Hopper-v3:
  <<: *mujoco-defaults

Walker2d-v3:
  <<: *mujoco-defaults

Humanoid-v3:
  <<: *mujoco-defaults
  n_timesteps: !!float 2e6

Swimmer-v3:
  <<: *mujoco-defaults
  gamma: 0.9999
  train_freq: 1
  gradient_steps: 1

FoRLHopper-v0:
  <<: *mujoco-defaults
  n_timesteps: !!float 5e5
  batch_size: 128
  buffer_size: 100000
  gamma: 0.999
  learning_rate: 0.0007321463574972058
  tau: 0.005
  train_freq: 4
  policy_kwargs: "dict(net_arch=[64, 64])"

FoRLHopperRandomNormal-v0:
  <<: *mujoco-defaults
  n_timesteps: !!float 5e5
  batch_size: 1024
  buffer_size: 1000000
  gamma: 0.9999
  learning_rate: 8.544528766204316e-05
  noise_std: 0.8703922600114818
  noise_type: "ornstein-uhlenbeck"
  tau: 0.02
  train_freq: 512
  policy_kwargs: "dict(net_arch=[256, 256])"

FoRLHalfCheetah-v0:
  <<: *mujoco-defaults
  n_timesteps: !!float 5e5
  batch_size: 100
  buffer_size: 1000000
  gamma: 0.99
  learning_rate: 0.0014644378357406005
  noise_std: 0.22195861713740578
  noise_type: "normal"
  tau: 0.05
  train_freq: 4
  policy_kwargs: "dict(net_arch=[256, 256])"

FoRLHalfCheetahRandomNormal-v0:
  <<: *mujoco-defaults
  n_timesteps: !!float 5e5
  batch_size: 128
  buffer_size: 100000
  gamma: 0.99
  learning_rate: 0.0007807680830532737
  noise_std: 0.533084903573579
  noise_type: "normal"
  tau: 0.08
  train_freq: 32
  policy_kwargs: "dict(net_arch=[256, 256])"

# === FoRL Envs ===
FoRLAcrobotRandomNormal-v0:
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  gamma: 0.98
  buffer_size: 200000
  learning_starts: 10000
  noise_type: "normal"
  noise_std: 0.1
  gradient_steps: -1
  train_freq: [1, "episode"]
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400, 300])"

FoRLPendulumRandomNormal-v0:
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  learning_starts: 10000
  gradient_steps: -1
  policy_kwargs: "dict(net_arch=[400, 300])"
  batch_size: 256
  buffer_size: 100000
  gamma: 0.9999
  learning_rate: 0.0022639514647602825
  tau: 0.02
  train_freq: 128

FoRLPendulum-v0:
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  learning_starts: 10000
  gradient_steps: -1
  policy_kwargs: "dict(net_arch=[400, 300])"
  batch_size: 128
  buffer_size: 100000
  gamma: 0.999
  learning_rate: 0.00033687847757567593
  tau: 0.02
  train_freq: 128

FoRLAcrobot-v0:
  n_timesteps: !!float 5e5
  policy: "MlpPolicy"
  gamma: 0.98
  buffer_size: 200000
  learning_starts: 10000
  noise_type: "normal"
  noise_std: 0.1
  gradient_steps: -1
  train_freq: [1, "episode"]
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400, 300])"
